resources:
  containers:
  - container: node12
    image: node:12.10-stretch
  - container: node10
    image: node:10.16-stretch
  - container: node8
    image: node:8.16-stretch

stages:

  - stage: Lint
    jobs:
      - job: LintJob
        container: node12
        steps:
          - script: |
            npm install
            npm run test:lint
            npm run test:types

  - stage: Unit
    jobs:
      - job: UnitJobNode12
        container: node12
        steps:
          - script: |
            npm run test:unit
      - job: UnitJobNode10
        container: node10
        steps:
          - script: |
            npm run test:unit
      - job: UnitJobNode8
        container: node8
        steps:
          - script: |
            npm run test:unit

  - stage: Build
    jobs:
      - job: BuildJob
        container: node12
        steps:
          - script |
            npm run build
