trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

resources:
  containers:
  - container: node12
    image: node:12.10-stretch-slim
  - container: node10
    image: node:10.16-stretch-slim
  - container: node8
    image: node:8.16-stretch-slim

stages:
  - stage: Tests
    jobs:
      - job: TestsJobNode12
        container: node12
        steps:
          - bash: |
              npm install && npm test
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: TestRun Node 12
          - task: PublishCodeCoverageResults@1
            displayName: "Publish Coverage Results"
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: "cobertura"
              summaryFileLocation: "coverage/cobertura-coverage.xml"
              reportDirectory: "coverage/lcov-report"
      - job: TestsJobNode10
        container: node10
        steps:
          - bash: |
              npm install && npm test
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: TestRun Node 10
      - job: TestsJobNode8
        container: node8
        steps:
          - bash: |
              npm install && npm test
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: TestRun Node 8
  - stage: BuildAndPublish
    jobs:
      - job: PublishJob
        container: node12
        steps:
          - bash: |
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && \
              npm install && \
              npm run build && \
              npm run build:publish -- $(Build.SourceBranch) && \
              rm -rf ~/.npmrc
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
            env:
              NPM_TOKEN: $(secretNpmToken)
