trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

resources:
  containers:
  - container: node12
    image: node:12.10-stretch-slim
  - container: node10
    image: node:10.16-stretch-slim
  - container: node8
    image: node:8.16-stretch-slim

stages:
  - stage: Lint
    jobs:
      - job: LintJob
        container: node12
        steps:
          - bash: |
              npm install
              npm run test:lint
              npm run test:types
  - stage: UnitTests
    jobs:
      - job: UnitTestsJobNode12
        container: node12
        steps:
          - bash: |
              npm install
              npm run test:unit
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: TestRun Node 12
          - task: PublishCodeCoverageResults@1
            displayName: "Publish Coverage Results"
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: "cobertura"
              summaryFileLocation: "coverage/cobertura-coverage.xml"
              reportDirectory: "coverage/lcov-report"
      - job: UnitTestsJobNode10
        container: node10
        steps:
          - bash: |
              npm install
              npm run test:unit
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: TestRun Node 10
      - job: UnitTestsJobNode8
        container: node8
        steps:
          - bash: |
              npm install
              npm run test:unit
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: TestRun Node 8
  - stage: Build
    jobs:
      - job: BuildJob
        container: node12
        steps:
          - bash: |
              npm install
              npm run build
  - stage: Publish
    jobs:
      - job: PublishJob
        container: node12
        steps:
          - bash: npm run publish
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
